# Repository Metadata
# Metadados do repositório para catalogação e descoberta

apiVersion: ifood/v2.6
kind: Repository
spec:
  contents:
    - name: custom-charts
      type: library
      subType: application
      impactLevel: low
      ownerLayerSlug: data-viz
      deployment:
        type: manual
      description: "Projeto de Custom Charts desenvolvidos com Muze Studio e ThoughtSpot Chart SDK para visualização de dados avançada no iFood"
      links:
        - type: repository
          url: "https://code.ifoodcorp.com.br/ifood/data/viz/custom-charts"
        - type: documentation
          url: "https://code.ifoodcorp.com.br/ifood/data/viz/custom-charts/-/tree/main/docs"
