include:
  - project: ifood/pipelines/gitlab-pipelines
    ref: ifood-docker-1-stable
    file: pipelines/ifood-docker/main.yml
  - local: node-gitlab-ci.yml

variables:
  _NODE_VERSION: v22.11.0
  CONTAINER_IMAGE_NAME: "$CI_REGISTRY_IMAGE/22"
  SERVICE_NAME: nodejs-golden-image
  BUILD_CONTEXT: "node-22"
  BUILD_ARGS: "VERSION=$_NODE_VERSION BASE_IMG_VERSION=$BASE_IMG_VERSION"
  BUILD_DOCKERFILE_PATH: "../Dockerfile"

# Fix BUILD_ARGS being overwritten
.before_build:
  before_script:
    - cp node_downloader.sh $BUILD_CONTEXT/
    - cp .executor $BUILD_CONTEXT/
    - cp 01-permissions.yaml $BUILD_CONTEXT/
    - export _BUILD_ARGS=$BUILD_ARGS
    - !reference [.golden_image, before_script]
    - export BUILD_ARGS="${BUILD_ARGS} ${_BUILD_ARGS}"

build_image:
  before_script:
    - !reference [.before_build, before_script]

build_image_multiarch:
  before_script:
    - !reference [.before_build, before_script]

.bridge_simple_project:
  variables:
    GOLDEN_IMG_TAG: "$CI_PIPELINE_IID"
    GOLDEN_IMG_NODE_VERSION: "22"
  rules:
    - if: $CI_MERGE_REQUEST_IID
  inherit:
    variables: false
  trigger:
    branch: main
    strategy: depend

bridge_node:
  extends: .bridge_simple_project
  trigger:
    project: ifood/docker-images/golden/test-projects/simple-project-gi-nodejs
